apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager
  labels:
    svc: user
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: user
      app: manager
  template:
    metadata:
      labels:
        svc: user
        app: manager
    spec:
      containers:
      - name: user-manager
        image: g1g1/delinkcious-user:0.2
        ports:
        - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: user-manager
spec:
  ports:
  - port: 7070
  selector:
    svc: user
    app: manager
